default: &default
  adapter: postgresql
  encoding: unicode
  host: <%= ENV.fetch("DB_HOST") {"db"} %>
  username: <%= ENV.fetch("DB_USER") %>
  password: <%= ENV.fetch("DB_PASSWORD") %>
  port: <%= ENV.fetch("DB_PORT") {5432} %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: <%= ENV.fetch("DEVELOPMENT_DB") {"development"}%>

production:
  <<: *default
  database: <%= ENV.fetch("PRODUCTION_DB") {"production"}%>

test:
  <<: *default
  database: test